# Generated by Django 3.0 on 2020-08-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='like',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
