# Generated by Django 3.0 on 2020-08-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200826_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
