# Generated by Django 3.0 on 2020-08-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
