# Generated by Django 3.0 on 2020-08-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_movie_premier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
