# Generated by Django 3.1 on 2020-08-31 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20200830_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set_Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.CharField(max_length=100, null=True)),
                ('time1', models.CharField(max_length=100, null=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='set_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.set_timing'),
        ),
    ]
