# Generated by Django 3.1 on 2020-08-31 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20200901_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie',
        ),
    ]
