# Generated by Django 3.1 on 2020-09-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.customer'),
        ),
    ]
