# Generated by Django 3.2.6 on 2021-08-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_booking_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='casting',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Movie_Type',
        ),
    ]
