# Generated by Django 3.1.4 on 2021-08-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20210810_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('seat', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('ticket', models.CharField(max_length=100, null=True)),
                ('set_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.set_timing')),
            ],
        ),
    ]
