# Generated by Django 3.1.4 on 2021-08-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie_time'),
        ),
    ]
