# Generated by Django 3.1.4 on 2021-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_auto_20210817_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screen',
            field=models.CharField(choices=[('Screen 1', '1'), ('Screen 2', '2'), ('Screen 3', '3'), ('Screen 4', '4'), ('Screen 5', '5')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.CharField(choices=[('Morning', '9:00 AM'), ('Noon', '12:00 PM'), ('Matinee', '3:00 PM'), ('Evening', '6:00 AM'), ('Night', '9:00 PM')], max_length=200, null=True),
        ),
    ]
