# Generated by Django 3.1.4 on 2021-08-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_auto_20210817_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='time',
        ),
    ]
