# Generated by Django 3.1.4 on 2021-08-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0023_remove_movie_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screen',
            field=models.IntegerField(default=0),
        ),
    ]
