# Generated by Django 3.2.7 on 2021-10-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0024_auto_20210817_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('platinum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('platinum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
            ],
        ),
    ]
