# Generated by Django 3.2.9 on 2021-11-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_auto_20211109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
