# Generated by Django 3.2.9 on 2021-11-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
