# Generated by Django 3.2.9 on 2021-11-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_alter_pending_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='set_timing',
            name='screen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
