# Generated by Django 3.2.9 on 2021-11-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_set_timing_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_time',
            name='screen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
