# Generated by Django 3.2.9 on 2021-11-17 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0030_movie_time_screen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set_timing',
            name='time1',
        ),
        migrations.AlterField(
            model_name='set_timing',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.movie_time'),
        ),
    ]
