# Generated by Django 3.2.9 on 2021-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0031_auto_20211117_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='screen',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
