# Generated by Django 3.2.9 on 2021-11-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_alter_movie_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_time',
            name='screen_id',
            field=models.IntegerField(null=True),
        ),
    ]
