# Generated by Django 3.2.9 on 2021-11-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0033_movie_time_screen_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screen1',
        ),
        migrations.DeleteModel(
            name='Screen2',
        ),
        migrations.DeleteModel(
            name='Screen3',
        ),
        migrations.DeleteModel(
            name='Screen4',
        ),
        migrations.DeleteModel(
            name='Screen5',
        ),
    ]
