# Generated by Django 3.2.9 on 2021-11-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0035_cats_seats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cats_seats',
            new_name='cats_seat',
        ),
    ]
