# Generated by Django 3.2.9 on 2021-11-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0036_rename_cats_seats_cats_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats_seat',
            name='seats_count',
            field=models.IntegerField(null=True),
        ),
    ]
