# Generated by Django 3.2.9 on 2021-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0038_cats_seat_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats_seat',
            name='seats_list',
            field=models.CharField(default=[[], [], [], [], []], max_length=1000, null=True),
        ),
    ]
