# Generated by Django 3.2.9 on 2021-11-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0039_alter_cats_seat_seats_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats_seat',
            name='seats_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cats_seat',
            name='seats_list',
            field=models.CharField(default='[[],[],[],[],[]]', max_length=1000, null=True),
        ),
    ]
