# Generated by Django 3.2.9 on 2021-11-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0040_auto_20211127_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cats_seat',
            name='seats_count',
            field=models.CharField(default=0, max_length=1000, null=True),
        ),
    ]
